spring:
  cloud:
    azure:
      compatibility-verifier:
        enabled: false
      keyvault:
        secret:
          property-sources[0]:
            name: spring-azure-apipet
            endpoint: https://spring-azure-apipet.vault.azure.net/
          property-source-enabled: true
    database:
      secret:
        value: ${spring-data-postgres-uri}